### ISSUE TITLE
Error on using "number of codings" as value

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#427]
![screenshot from 2015-11-15 20 10 54](https://cloud.githubusercontent.com/assets/6438205/11170455/1108b16a-8bd5-11e5-8064-c2e68353719e.png)

When doing a codingjob query with "number of codings", the server gives an error. Log shows:

```
[2015-11-15 20:12:06,474: ERROR/MainProcess] Task amcat.models.task.amcat_task[12baddde-5244-45e3-974a-57ea3f588954] raised unexpected: ProgrammingError('missing FROM-clause entry for table "t_coded_articles"\nLINE 1: SELECT codings_values.intval,COUNT(DISTINCT(T_coded_articles...\n                                                    ^\n',)
Traceback (most recent call last):
  File "/srv/amcat_dev/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/amcat_dev/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/amcat_dev/amcat/amcat/models/task.py", line 50, in amcat_task
    return handler.run_task()
  File "/srv/amcat_dev/amcat/amcat/scripts/query/queryaction.py", line 97, in run_task
    return query_action.run(query_action.get_form())
  File "/srv/amcat_dev/amcat/amcat/scripts/query/codings_aggregation.py", line 253, in run
    aggregation = sorted(aggregation, key=to_sortable_tuple)
  File "/srv/amcat_dev/amcat/amcat/tools/aggregate_orm/aggregate.py", line 140, in _get_aggregate
    aggregations = list(self._execute_sqls(queries))
  File "/srv/amcat_dev/amcat/amcat/tools/aggregate_orm/aggregate.py", line 133, in _execute_sqls
    return list(threadpool.map(self._execute_sql, queries))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ProgrammingError: missing FROM-clause entry for table "t_coded_articles"
LINE 1: SELECT codings_values.intval,COUNT(DISTINCT(T_coded_articles...
                                                    ^
```

**Comment by nruigrok** [comment]
(Dit is overigens niet zo heel erg omdat # of coding values wel gewoon werkt. Wat is het verschil eigenlijk?)

**Comment by martijnbastiaan** [comment]
Fixed in master.
