### ISSUE TITLE
unicode in query causes error in logging

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#537]
query: https://amcat.nl/navigator/projects/1/query/?query=102&sets=29330#summary

```
[2016-05-23 15:34:07,690 ERROR root:13] API Exception
Traceback (most recent call last):
  File "/srv/amcat/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "./api/rest/query/viewset.py", line 133, in post
    task_handler = qa.run_delayed()
  File "./amcat/scripts/query/queryaction.py", line 209, in run_delayed
    if not form.is_valid():
  File "/srv/amcat/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "/srv/amcat/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/srv/amcat/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 393, in full_clean
    self._clean_form()
  File "/srv/amcat/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 417, in _clean_form
    cleaned_data = self.clean()
  File "./amcat/scripts/forms/selection.py", line 261, in clean
    SelectionSearch(self).get_query()
  File "./amcat/tools/caching.py", line 64, in inner
    return _set_cache_value(cache, func.__name__, func(self))
  File "./amcat/tools/keywordsearch.py", line 99, in get_query
    return ' OR '.join('(%s)' % q.query for q in self.get_queries()) or None
  File "./amcat/tools/caching.py", line 64, in inner
    return _set_cache_value(cache, func.__name__, func(self))
  File "./amcat/tools/keywordsearch.py", line 126, in get_queries
    return [q for q in resolved if not q.label.startswith("_")]
  File "./amcat/tools/keywordsearch.py", line 395, in resolve_queries
    log.warn("Resolving queries {queries}, {codebook}:{label_language} -> {replacement_language}".format(**locals()))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)
```

**Comment by CJStuart** [comment]
fixed in 3ba12eb
