### ISSUE TITLE
Installation problem with "python -m amcat.manage migrate"

### ISSUE THREAD

**Issue by aemal** [amcat/amcat#546]
Hello!

I am trying to install AmCAT from last several hours and yet no success. I tried to fix most of the problems by googling, found some issues which I will let you know later, but now I am facing the following error while executing the command "python -m amcat.manage migrate" in python 2.7:

```
(amcat34_3-env) aemal@aemal-Latitude-E6410:~/amcat34_3$ python -m amcat.manage migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, annotator, markdown_deux, compressor, api, accounts, method_override, django_extensions, rest_framework, navigator
  Apply all migrations: authtoken, sessions, admin, djcelery, sites, auth, contenttypes, amcat
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying amcat.0001_initial... OK
  Applying amcat.0002_query... OK
  Applying amcat.0003_articleset_featured... OK
  Applying amcat.0004_auto_20150418_1656... OK
  Applying amcat.0005_code_label... OK
  Applying amcat.0006_auto_20150907_1238... OK
  Applying amcat.0007_optionalschemas... OK
  Applying amcat.0008_auto_20151028_1300... OK
  Applying amcat.0009_recentprojects... OK
  Applying amcat.0010_remove_syntax_rules... OK
  Applying amcat.0011_article_length_not_null... OK
  Applying amcat.0010_task_user_null... OK
  Applying amcat.0012_merge... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying authtoken.0001_initial... OK
  Applying djcelery.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
Installed 54 object(s) from 1 fixture(s)
[2016-07-19 15:31:12,236 WARNING elasticsearch:76] HEAD /amcat [status:404 request:0.002s]
[2016-07-19 15:31:12,236 WARNING elasticsearch:76] HEAD /amcat [status:404 request:0.002s]
[2016-07-19 15:31:12,376 WARNING elasticsearch:76] PUT /amcat [status:400 request:0.139s]
[2016-07-19 15:31:12,376 WARNING elasticsearch:76] PUT /amcat [status:400 request:0.139s]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aemal/amcat34_3/amcat/manage/__main__.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 225, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/django/core/management/sql.py", line 288, in emit_post_migrate_signal
    db=db)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "amcat/tools/initialize.py", line 65, in initialize
    amcates.ES().check_index()
  File "amcat/tools/amcates.py", line 330, in check_index
    self.create_index()
  File "amcat/tools/amcates.py", line 318, in create_index
    self.es.indices.create(self.index, body)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 96, in create
    params=params, body=body)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/aemal/amcat34_3-env/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'IndexCreationException[[amcat] failed to create index]; nested: IllegalArgumentException[Custom Analyzer [default] failed to find filter under name [icu_folding]]; ')
```

and following in python 3.4:

```
(env) aemal@aemal-Latitude-E6410:~/amcat$ python -m amcat.manage migrate
Traceback (most recent call last):
  File "/home/aemal/anaconda3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aemal/anaconda3/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aemal/amcat/amcat/manage/__main__.py", line 13, in <module>
    import settings
  File "/home/aemal/amcat/settings/__init__.py", line 21, in <module>
    from .base import *
  File "/home/aemal/amcat/settings/base.py", line 25, in <module>
    from amcat.tools.toolkit import random_alphanum
  File "/home/aemal/amcat/amcat/tools/toolkit.py", line 500
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```

Thanks,
Aemal

**Comment by martijnbastiaan** [comment]
The master branch is Python 3 enabled. The branch  you're using is indeed Python 2. Did you install the analysis-icu plugin for elastic?

```bash
cd /usr/share/elasticsearch
sudo bin/plugin install mobz/elasticsearch-head
sudo bin/plugin install analysis-icu
sudo bin/plugin install amcat/hitcount
```

**Comment by aemal** [comment]
Yes! I am using master branch and python 3.4 and yes I installed all the plugins. Now I have figured out that I have to manually change the toolkit.py and several other files, it is just a python3 syntax issue. I hope this will solve the problem.

**Comment by martijnbastiaan** [comment]
I'm a little bit confused. Your stacktrace yields a SyntaxError on line 500 of toolkit.py. In the master branch this line does not exist: https://github.com/amcat/amcat/blob/master/amcat/tools/toolkit.py.

Could you paste the output of `git branch` and `git rev-parse HEAD`?

**Comment by aemal** [comment]
Oh! You know what! The clone command:

`git clone -b release-3.4 https://github.com/amcat/amcat.git`

Gives me the file with line 500 in toolkit.py and the clone command:

`git clone https://github.com/amcat/amcat.git`

Gives me the one in the master branch.

git branch result:
* release-3.4

git rev-parse HEAD result:
fa16d4262fa4f569874c38d8d6d7c9c37324dcd6

**Comment by aemal** [comment]
Dam!
It was all due to a wrong branch which I copied from the readme file. Now that I cloned from the master branch, everything worked like a charm but now that I run the web server while visiting "http://127.0.0.1:8000/", I see the following error:

```
ImportError at /
Could not import 'api.rest.tablerenderer.CSVRenderer' for API setting 'DEFAULT_RENDERER_CLASSES'. ImportError: /home/aemal/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC.
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.8.1
Exception Type:	ImportError
Exception Value:	
Could not import 'api.rest.tablerenderer.CSVRenderer' for API setting 'DEFAULT_RENDERER_CLASSES'. ImportError: /home/aemal/anaconda3/bin/../lib/libreadline.so.6: undefined symbol: PC.
Exception Location:	/home/aemal/env/lib/python3.4/site-packages/rest_framework/settings.py in import_from_string, line 176
Python Executable:	/home/aemal/env/bin/python
Python Version:	3.4.3
Python Path:	
['/home/aemal/amcat/amcat/manage',
 '/home/aemal/amcat',
 '/home/aemal/anaconda3/lib/python34.zip',
 '/home/aemal/anaconda3/lib/python3.4',
 '/home/aemal/anaconda3/lib/python3.4/plat-linux',
 '/home/aemal/anaconda3/lib/python3.4/lib-dynload',
 '/home/aemal/env/lib/python3.4/site-packages',
 '/home/aemal/amcat']
Server time:	Tue, 19 Jul 2016 22:52:14 +0200
```

**Comment by aemal** [comment]
Hello!

So should I clone it from:

git clone -b release-3.4 https://github.com/amcat/amcat.git

or this:

git clone https://github.com/amcat/amcat.git

Please read the details of both in my 3rd last comment.

**Comment by vanatteveldt** [comment]
Hey Aemal,

Sorry, the -b release-3.4 should not have been there in the master readme, it ended up in there from an automatic merge, my bad. 

To be clear, to install the 'master' branch (which is under development, i.e. highly unstable and probably unusable, so should be used mainly if you're interested in contributing to development), you need to `git clone https://github.com/amcat/amcat.git` and follow the instructions from https://github.com/amcat/amcat/blob/master/README.md. 

To install the 3.4 branch (which is the currently released version and should work fine), you need to follow the instructions from https://github.com/amcat/amcat/blob/release-3.4/README.md

-- Wouter

**Comment by aemal** [comment]
Thank you so much! I was so much confused and spent hours debugging stuff. I hope this will work.
