### ISSUE TITLE
update hitcount plugin for elastic 2.3.4

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#548]
```
$ sudo bin/plugin install amcat/hitcount
-> Installing amcat/hitcount...
Trying https://github.com/amcat/hitcount/archive/master.zip ...
Downloading ..................DONE
Verifying https://github.com/amcat/hitcount/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [hitcount] is incompatible with Elasticsearch [2.3.4]. Was designed for version [2.1.1]
```

I think we need to add a different release compiled against a different elasticsearch version, but my java days are 15 years ago :)

**Comment by martijnbastiaan** [comment]
Fixed! Users now need to specify elastic version upon installing. For example:

```
sudo bin/plugin install amcat/hitcunt/2.3.4
```

**Comment by martijnbastiaan** [comment]
See: https://discuss.elastic.co/t/must-i-roll-a-specific-plugin-version-for-each-release-x-java-and-let-users-specify-it-upon-installation/56385

**Comment by vanatteveldt** [comment]
Thanks for fixing this. Unfortunately, I get a java error when I use the new plugin:


```
[2016-07-28 11:18:37,498][DEBUG][action.search            ] [Sidewinder] [test_amcat_11159][3], node[itYhwcj8S86NPNCgXUwJjQ], [P], v[2], s[STARTED], a[id=pYQLPcvtR8CRi_7xa5Z00A]: Failed to execute [org.elasticsearch.action.search.SearchRequest@5964d191]
RemoteTransportException[[Sidewinder][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AbstractMethodError[org.apache.lucene.search.similarities.Similarity.computeWeight(Lorg/apache/lucene/search/CollectionStatistics;[Lorg/apache/lucene/search/TermStatistics;)Lorg/apache/lucene/search/similarities/Similarity$SimWeight;];
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AbstractMethodError[org.apache.lucene.search.similarities.Similarity.computeWeight(Lorg/apache/lucene/search/CollectionStatistics;[Lorg/apache/lucene/search/TermStatistics;)Lorg/apache/lucene/search/similarities/Similarity$SimWeight;];
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:366)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:378)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError: org.apache.lucene.search.similarities.Similarity.computeWeight(Lorg/apache/lucene/search/CollectionStatistics;[Lorg/apache/lucene/search/TermStatistics;)Lorg/apache/lucene/search/similarities/Similarity$SimWeight;
	at org.apache.lucene.search.similarities.PerFieldSimilarityWrapper.computeWeight(PerFieldSimilarityWrapper.java:52)
	at org.apache.lucene.search.TermQuery$TermWeight.<init>(TermQuery.java:76)
	at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:198)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:904)
	at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:57)
	at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:239)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:904)
	at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:887)
	at org.elasticsearch.search.internal.ContextIndexSearcher.createNormalizedWeight(ContextIndexSearcher.java:100)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
	... 12 more
```

The error is triggered by most amcates tests, e.g.:

```
======================================================================
FAIL: test_scores (amcat.tools.tests.test_amcates.TestAmcatES)
test if scores (and matches) are as expected for various queries
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wva/amcat/amcat/tools/amcattest.py", line 364, in inner
    return func(*args, **kargs)
  File "/home/wva/amcat/amcat/tools/tests/test_amcates.py", line 259, in test_scores
    self.assertEqual(q("test"), {"a": 1})
AssertionError: {} != {'a': 1}
- {}
+ {'a': 1}
```

which runs fine if I remove the hitcountsimilarity from elasticsearch.yml

Some system info:
```
wva@study-linux: {master} ~/amcat$ uname -a
Linux study-linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
wva@study-linux: {master} ~/amcat$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
wva@study-linux: {master} ~/amcat$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
wva@study-linux: {master} ~/amcat$ curl localhost:9200
{
  "name" : "Sidewinder",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.4",
    "build_hash" : "e455fd0c13dceca8dbbdbb1665d068ae55dabe3f",
    "build_timestamp" : "2016-06-30T11:24:31Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by vanatteveldt** [comment]
@martijnbastiaan  has this been fixed? The tests seem to give different errors now :)

**Comment by vanatteveldt** [comment]
@martijnbastiaan friendly bump :)

**Comment by martijnbastiaan** [comment]
duly noted

**Comment by martijnbastiaan** [comment]
Alright, permanentely fixed. Please run:

```bash
cd /usr/share/elasticsearch
sudo bin/plugin remove hitcount
sudo bin/plugin install amcat/hitcount/2.3.4
sudo systemctl restart elasticsearch.service
```

**Comment by martijnbastiaan** [comment]
I'll be adding instructions to the hitcount README asap to prevent the same kind of error in the future :)
