### ISSUE TITLE
Error on Uploading Articles

### ISSUE THREAD

**Issue by aemal** [amcat/amcat#549]
After a gazillion hours of working I realized that most of the problems I was facing were due to Ubuntu 16.04. After installing Ubuntu 14.04, everything worked like a charm except bower, it was giving time out, I had to install all the dependencies one by one and took an incredible amount of time, even more than 2 hours. Now I face an error while uploading the articles using plain text (directly by filling the Text field, not by importing a text file):

Status:	FAILURE
Message:	AttributeError: 'NoneType' object has no attribute 'strip'

Thanks a heap for your usual superb support!

**Comment by vanatteveldt** [comment]
Hey Aemal,

Strange, I don't see a real reason why 16.04 won't work (and I'm actually sure 3.4 works here and I run 16.04). Only problem was a kombu version problem which was fixed yesterday. Anyway, great to hear that it worked.

I have to admit that the uploader is quite a mess, it's one of the priorities for 3.5. In any case, you should be able to see a better error message in your celery worker log or console output. Can you paste that error here?

Cheers, Wouter

**Comment by aemal** [comment]
Hello Wouter,

It is truly strange, I have also kept struggling on 16.04 having a belief that it should not be a reason, most probably it was due to a mess I did which was not cleaned, as I reinstalled it several times. How long does the bower install takes at your end? I have 50Mbit internet and it took over 2 hours (I had to put it individually in bower.json, otherwise it would give 404 error).

Let me explain how I get the error in the uploader. In "Plain Text" I select article set, fill medium field, enter date "2010-02-02" and copy a bunch of text in the Text field. Following is the celery console log:

```

[2016-07-26 09:04:16,014: INFO/MainProcess] Received task: amcat.models.task.amcat_task[2a144f8a-b831-4e54-88c4-0ea7086a06d9]
[2016-07-26 09:04:16,028: INFO/Worker-3] [10%] 10 / 100 u'Importing Text from None into Test Project Name'
[2016-07-26 09:04:17,152: INFO/Worker-3] [30%] 30 / 100 'Parsing file 0/1: None'
[2016-07-26 09:04:17,162: ERROR/MainProcess] Task amcat.models.task.amcat_task[2a144f8a-b831-4e54-88c4-0ea7086a06d9] raised unexpected: AttributeError("'NoneType' object has no attribute 'strip'",)
Traceback (most recent call last):
  File "/home/aemal/amcat-env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/aemal/amcat-env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/aemal/amcat/amcat/models/task.py", line 50, in amcat_task
    return handler.run_task()
  File "/home/aemal/amcat/navigator/views/scriptview.py", line 93, in run_task
    result = script.run()
  File "/home/aemal/amcat/amcat/scripts/article_upload/upload.py", line 163, in run
    articles += list(self.parse_file(f))
  File "/home/aemal/amcat/amcat/scripts/article_upload/upload.py", line 145, in parse_file
    for a in self._scrape_unit(unit):
  File "/home/aemal/amcat/amcat/scripts/article_upload/upload.py", line 203, in _scrape_unit
    result =  self.parse_document(document)
  File "/home/aemal/amcat/amcat/scripts/article_upload/text.py", line 150, in parse_document
    if not metadata["headline"].strip():
AttributeError: 'NoneType' object has no attribute 'strip'

```

I can see in the error log that the upload function is called, although I have not uploaded any file, but I wanted to upload some text directly to the text field. This works fine with uploading a text file (with special format i.e. 2010-02-02_Something.txt).

Sincerely,
Aemal

**Comment by vanatteveldt** [comment]
You need to fill in a headline value as well (you an just enter a dash or something if you really don't want a headline). Sorry for the bad error message, @CJStuart  is working on updating the upload screen as we type :)
