### ISSUE TITLE
Error on Uploading Articles

### ISSUE THREAD

**Issue by aemal** [amcat/amcat#550]
I have an old installation of amcat on a server which is giving the following error on uploading articles:

out put from the front page:

```
Exception at /navigator/projects/8/articlesets/upload/1/
No articles were imported
Request Method: POST
Request URL:    http://komepol.west.uni-koblenz.de/navigator/projects/8/articlesets/upload/1/
Django Version: 1.6.5
Exception Type: Exception
Exception Value:    
No articles were imported
Exception Location: /usr/local/lib/python2.7/dist-packages/amcat/scripts/article_upload/upload.py in run, line 159
Python Executable:  /usr/bin/python
Python Version: 2.7.6
Python Path:    
['/home/ubuntu/westcat/amcat/manage',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/ubuntu/westcat']
Server time:    Tue, 26 Jul 2016 14:50:01 +0200
```

Output from the server console:

```
Exception: No articles were imported
[2016-07-26 15:00:57,980 ERROR django.request:224] Internal Server Error: /navigator/projects/8/articlesets/upload/1/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/navigator/views/projectview.py", line 95, in dispatch
    request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 171, in post
    return self.form_valid(form)
  File "/usr/local/lib/python2.7/dist-packages/navigator/views/articleset_views.py", line 203, in form_valid
    self.run_form(form)
  File "/usr/local/lib/python2.7/dist-packages/navigator/views/scriptview.py", line 50, in run_form
    self.result =  self.script_object.run()
  File "/usr/local/lib/python2.7/dist-packages/amcat/scripts/article_upload/upload.py", line 159, in run
    raise Exception("No articles were imported")
Exception: No articles were imported
[26/Jul/2016 15:00:58] "POST /navigator/projects/8/articlesets/upload/1/ HTTP/1.1" 500 155787

```

If I enter a unique value in the section field it works all the time. This error is driving me crazy, I went through those files in the trace, but no clue. Everything is running fine.

Sincerely,
Aemal

**Comment by vanatteveldt** [comment]
Hey Aemal,

This issue seems to have slipped through the cracks during the summer, are you still having problems?

-- Wouter
