### ISSUE TITLE
copy_articles fails from 3.4 -> 3.5

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#585]
@joepschaper reported in a separate issue (https://github.com/amcat/amcat/issues/577)
```
joep@joep-K73SJ:~$ python3 -m amcatclient.copy_articles https://amcat.nl
http://localhost:8000 36 23560 1
[2017-04-12 14:25:51,760 INFO root] Created set 3:Le Monde 3 in project 1
[2017-04-12 14:26:27,989 INFO root] Copying batch 1: 100 articles
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File
"/usr/local/lib/python3.6/site-packages/amcatclient/copy_articles.py", line
113, in <module>
    args.batch_size, args.from_page)
  File
"/usr/local/lib/python3.6/site-packages/amcatclient/copy_articles.py", line
78, in copy_articles
    trg_api.create_articles(trg_project, trg_set, batch)
  File "/usr/local/lib/python3.6/site-packages/amcatclient/amcatclient.py",
line 291, in create_articles
    return self.request(url, method='post', data=json_data, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/amcatclient/amcatclient.py",
line 203, in request
    return check(r, expected_status=expected_status)
  File "/usr/local/lib/python3.6/site-packages/amcatclient/amcatclient.py",
line 113, in check
    raise APIError(response.status_code, msg, url, response.text)
amcatclient.amcatclient.APIError: [Errno 500] Request '
http://localhost:8000/api/v4/projects/1/articlesets/3/articles/?format=json'
returned code 500, expected 201. Response written to /tmp/tmpeqk1zxnf.txt: '
http://localhost:8000/api/v4/projects/1/articlesets/3/articles/?format=json':
None; None
```

Contents of /tmp/tmpeqk1zxnf.txt:
```{json}
{"detail":"Value can not be None. Delete it
instead!","exception_type":"ValueError"}
```

It seems copy_articles might not work well on 3.5, or between 3.4 and 3.5. I'll have a look.

**Comment by joepschaper** [comment]
Would it be possible to lift the search string word limit cap until my
docker is up and running so that I can move on with my project?

**Comment by vanatteveldt** [comment]
(closing due to inaction)
