### ISSUE TITLE
Calculated fields in query/article list don't work

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#637]
I tried doing a query using article list as the output option, and tested all column options. The static and dynamic properties work fine (the table showing the article list loads pretty quickly). However, when I select either one of the calculated fields (# hits per keyword or keyword in context, in addition to the default columns or only that calculated field as the only column) amcat says 'processing' and never (> 10 minutes now) loads the table:

<img width="1018" alt="hits per keyword blijft hangen" src="https://user-images.githubusercontent.com/6417728/28974305-45d76c06-7936-11e7-8d7c-42c3a1f5b5bf.png">

and

<img width="1028" alt="kwic blijft ook hangen" src="https://user-images.githubusercontent.com/6417728/28974318-511e654c-7936-11e7-8eab-beae6ef61d17.png">

**Comment by vanatteveldt** [comment]
I can confirm the problem. 

Log message for keyword-in-context:

```
[pid: 15031|app: 0|req: 1251/3550] 82.161.112.61 () {58 vars in 1201 bytes} [Fri Aug  4 18:08:20 2017] POST /api/v4/search => generated 1254 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 106 bytes (1 switches on core 0)
[2017-08-04 18:08:20,488 DEBUG amcat.tools.amcates:410] Search with body:
 {'highlight': {'fields': {'text': {'fragment_size': 100,
                                   'no_match_size': 100,
                                   'number_of_fragments': 3,
                                   'require_field_match': False},
                          'title': {'no_match_size': 100,
                                    'require_field_match': False}},
               'post_tags': ['</mark>'],
               'pre_tags': ['<mark>']},
 'query': {'constant_score': {'query': {'bool': {'filter': [{'terms': {'sets': ['35841']}}],
                                                 'must': {'bool': {'should': [{'wildcard': {'_all': 'chicken*'}},
                                                                              {'wildcard': {'_all': 'chicken*'}}]}}}}}},
 'track_scores': True}
[2017-08-04 18:08:20,503 ERROR root:14] API Exception
Traceback (most recent call last):
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/fields.py", line 384, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/fields.py", line 75, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'Result' object has no attribute 'lead'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "./api/rest/resources/search.py", line 258, in get
    return super(SearchResource, self).get(request, *args, **kwargs)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/serializers.py", line 658, in data
    ret = super(ListSerializer, self).data
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/serializers.py", line 223, in data
    self._data = self.to_representation(self.instance)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/serializers.py", line 598, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/serializers.py", line 598, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/serializers.py", line 447, in to_representation
    attribute = field.get_attribute(instance)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/fields.py", line 401, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `lead` on serializer `SearchResourceSerialiser`.
The serializer field might be named incorrectly and not match any attribute or key on the `Result` instance.
Original exception text was: 'Result' object has no attribute 'lead'.
```

Log message for hits per keyword:
```
[pid: 15027|app: 0|req: 1023/3556] 82.161.112.61 () {58 vars in 1201 bytes} [Fri Aug  4 18:10:06 2017] POST /api/v4/search => generated 1052 bytes in 21 msecs (HTTP/1.1 200) 3 headers in 106 bytes (1 switches on core 0)
[2017-08-04 18:10:06,678 DEBUG amcat.tools.amcates:410] Search with body:
 {'highlight': {'fields': {'text': {'fragment_size': 100,
                                   'no_match_size': 100,
                                   'number_of_fragments': 3,
                                   'require_field_match': False},
                          'title': {'no_match_size': 100,
                                    'require_field_match': False}},
               'post_tags': ['</mark>'],
               'pre_tags': ['<mark>']},
 'query': {'constant_score': {'query': {'bool': {'filter': [{'terms': {'sets': ['35841']}}],
                                                 'must': {'bool': {'should': [{'wildcard': {'_all': 'chicken*'}},
                                                                              {'wildcard': {'_all': 'chicken*'}}]}}}}}},
 'track_scores': True}
[2017-08-04 18:10:06,709 DEBUG amcat.tools.amcates:410] Search with body:
 {'query': {'bool': {'filter': [{'ids': {'values': [182826179]}}],
                    'must': {'wildcard': {'_all': 'chicken*'}}}}}
[2017-08-04 18:10:06,767 ERROR root:14] API Exception
Traceback (most recent call last):
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "./api/rest/resources/search.py", line 258, in get
    return super(SearchResource, self).get(request, *args, **kwargs)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/rest_framework/generics.py", line 172, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "./api/rest/pagination.py", line 73, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
  File "./api/rest/resources/search.py", line 110, in __getitem__
    for hit in self.es.query_all(q.query, filters=filters, fields=[]):
  File "./amcat/tools/amcates.py", line 468, in query_all
    result = self.query(*args, **kargs)
  File "./amcat/tools/amcates.py", line 462, in query
    result = self.search(body, _source=_source, **kwargs)
  File "./amcat/tools/amcates.py", line 411, in search
    return self.es.search(body=body, **kargs)
  File "/srv/amcat_preview/amcat/env/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: search() got an unexpected keyword argument 'fields'
```
