### ISSUE TITLE
Error when aggregating on 'number of codings'

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#687]
Bij query met codingjobs krijg je een error als je 'number of codings' selecteert (zie onder). Number of coded values gaat wel goed (maar het verschil tussen die twee is me eigenlijk ook niet duidelijk).

![image](https://user-images.githubusercontent.com/6438205/42900962-936bdfc8-8aca-11e8-84ec-c0f1bffb1432.png)

```
jul 18 20:36:48 amcat2 python[3817]: [2018-07-18 20:36:48,406: INFO/MainProcess] Received task: amcat.models.task.amcat_task[c36250b9-9326-4365-8c64-2aab6c4170ed]
jul 18 20:36:48 amcat2 python[3817]: [2018-07-18 20:36:48,517: INFO/Worker-4] [0.0%] Task started, running CodingAggregationAction..
jul 18 20:36:48 amcat2 python[3817]: [2018-07-18 20:36:48,610: INFO/Worker-4] [1.0%] Executing query..
jul 18 20:36:48 amcat2 python[3817]: [2018-07-18 20:36:48,835: INFO/Worker-4] [11.0%] Found 6 articles. Aggregating..
jul 18 20:36:48 amcat2 python[3817]: [2018-07-18 20:36:48,890: ERROR/MainProcess] Task amcat.models.task.amcat_task[c36250b9-9326-4365-8c64-2aab6c4170ed] raised unexpected: ProgrammingError('missing FROM-clause entry for table "t_coded_articles"\nLINE 1: SELECT codings_values.intval,COUNT(DISTINCT(T_coded_articles...\n                                                    ^\n',)
jul 18 20:36:48 amcat2 python[3817]: Traceback (most recent call last):
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/env/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
jul 18 20:36:48 amcat2 python[3817]:     R = retval = fun(*args, **kwargs)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/env/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
jul 18 20:36:48 amcat2 python[3817]:     return self.run(*args, **kwargs)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/amcat/models/task.py", line 48, in amcat_task
jul 18 20:36:48 amcat2 python[3817]:     return handler.run_task()
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/amcat/scripts/query/queryaction.py", line 111, in run_task
jul 18 20:36:48 amcat2 python[3817]:     result = query_action.run(form)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/amcat/scripts/query/codings_aggregation.py", line 254, in run
jul 18 20:36:48 amcat2 python[3817]:     aggregation = sorted(aggregation, key=to_sortable_tuple)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/amcat/tools/aggregate_orm/aggregate.py", line 145, in _get_aggregate
jul 18 20:36:48 amcat2 python[3817]:     aggregations = list(self._execute_sqls(queries))
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/amcat/tools/aggregate_orm/aggregate.py", line 134, in _execute_sqls
jul 18 20:36:48 amcat2 python[3817]:     return list(threadpool.map(self._execute_sql, queries))
jul 18 20:36:48 amcat2 python[3817]:   File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
jul 18 20:36:48 amcat2 python[3817]:     return self._map_async(func, iterable, mapstar, chunksize).get()
jul 18 20:36:48 amcat2 python[3817]:   File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
jul 18 20:36:48 amcat2 python[3817]:     raise self._value
jul 18 20:36:48 amcat2 python[3817]:   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
jul 18 20:36:48 amcat2 python[3817]:     result = (True, func(*args, **kwds))
jul 18 20:36:48 amcat2 python[3817]:   File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
jul 18 20:36:48 amcat2 python[3817]:     return list(map(*args))
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/amcat/tools/aggregate_orm/aggregate.py", line 122, in _execute_sql
jul 18 20:36:48 amcat2 python[3817]:     c.execute(query)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
jul 18 20:36:48 amcat2 python[3817]:     return self.cursor.execute(sql, params)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/env/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
jul 18 20:36:48 amcat2 python[3817]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/env/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
jul 18 20:36:48 amcat2 python[3817]:     raise value.with_traceback(tb)
jul 18 20:36:48 amcat2 python[3817]:   File "/srv/amcat_bzk/amcat/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 62, in execute
jul 18 20:36:48 amcat2 python[3817]:     return self.cursor.execute(sql)
jul 18 20:36:48 amcat2 python[3817]: django.db.utils.ProgrammingError: missing FROM-clause entry for table "t_coded_articles"
jul 18 20:36:48 amcat2 python[3817]: LINE 1: SELECT codings_values.intval,COUNT(DISTINCT(T_coded_articles...
```

**Comment by martijnbastiaan** [comment]
@CJStuart wil jij deze overnemen?

**Comment by CJStuart** [comment]
Ja, ik zal ernaar kijken
