### ISSUE TITLE
query API: Result window is too large

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#693]
If you use the API to query on a large set that returns more than 10k results, it gives an error: `Result window is too large, from + size must be less than or equal to: [10000]`

Not clear whether this is a server setting or a change in the elasticsearch API, but I suppose we should move to the scroll API to get more results?

```
[2018-08-20 14:33:31,921 ERROR root:14] API Exception
Traceback (most recent call last):
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "./api/rest/resources/search.py", line 262, in get
    return super(SearchResource, self).get(request, *args, **kwargs)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/rest_framework/generics.py", line 172, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "./api/rest/pagination.py", line 73, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/django/core/paginator.py", line 55, in page
    return self._get_page(self.object_list[bottom:top], number, self)
  File "./api/rest/resources/search.py", line 99, in __getitem__
    **query_kargs
  File "./amcat/tools/amcates.py", line 509, in query
    result = self.search(body, _source=_source, **kwargs)
  File "./amcat/tools/amcates.py", line 456, in search
    return self.es.search(body=body, **kargs)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/srv/amcat_autnes/amcat/env/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(500, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [11000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')
```

**Comment by vanatteveldt** [comment]
(in reaction on error report from @daevil)
